version: '3.8'

services:
  flask-app:
    image: python:3.9-slim
    container_name: flask_app
    ports:
      - "5001:5000"
    volumes:
      - .:/app               # Mounts the entire project directory to /app in the container
      - ./debug.log:/app/debug.log  # Mounts the debug.log file for direct access
    working_dir: /app
    env_file:
      - .env                 # Loads environment variables from .env file located in the project directory
    command: >
      sh -c "chmod +x ./generate_certs.sh; ./generate_certs.sh && 
            pip install -r requirements.txt && 
            flask run --host=0.0.0.0 --port=5000 --cert=cert.pem --key=key.pem"
